name: bump-ferdium-casks
on:
  release:
    types: [published]
  # Manual trigger from the UI
  workflow_dispatch:

jobs:
  bump-casks:
    runs-on: macos-latest
    steps:
    - uses: macauley/action-homebrew-bump-cask@v1
      with:
        # Required, custom GitHub access token with only the 'public_repo' scope enabled
        token: ${{secrets.HOMEBREW_FERDIUM_PUBLISH_TOKEN}}
        # Bump all outdated casks in this tap
        tap: ferdium/homebrew-ferdium
        # Bump only these casks if outdated
        cask: ferdium-nightly
        livecheck: true
        dryrun: false
# TODO: Need separate ones for the beta and public builds
