name: Verify secrets

on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Check token
      run: |
        if [ ${{ secrets.PUBLISH_TOKEN }} != '' ]; then
          echo "Token is set and ready for use."
        else
          echo "Token is not available for this workflow."
        fi
    - name: Check certifs for Mac
      run: |
        if [ ${{ secrets.CSC_LINK }} != '' && ${{ secrets.CSC_KEY_PASSWORD }} != '' ]; then
          echo "- Certificate variables for Mac correctly set!"
        else
          echo "- Error with values contained in CSC_* certificates."
        fi
    - name: Check certifs for Windows
      run: |
        if [ ${{ secrets.WIN_CSC_LINK }} != '' && ${{ secrets.WIN_CSC_KEY_PASSWORD }} != '' ]; then
          echo "- Certificate variables for Windows correctly set!"
        else
          echo "- Error with values contained in WIN_CSC_* certificates."
        fi
  install_winget:
    runs-on: windows-latest
    steps:
      - name: "Install winget"
        run: |
          $ErrorActionPreference = 'Stop'

          iwr $(iwr 'https://store.rg-adguard.net/api/GetFiles' -Method 'POST' -ContentType 'application/x-www-form-urlencoded' -Body 'type=PackageFamilyName&url=Microsoft.VCLibs.140.00_8wekyb3d8bbwe&ring=RP&lang=en-US' -UseBasicParsing | Foreach-Object Links | Where-Object outerHTML -match 'Microsoft.VCLibs.140.00_.+_x64__8wekyb3d8bbwe.appx' | Foreach-Object href) -OutFile $env:TEMP\vclibs.appx
          iwr $(iwr 'https://store.rg-adguard.net/api/GetFiles' -Method 'POST' -ContentType 'application/x-www-form-urlencoded' -Body 'type=PackageFamilyName&url=Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe&ring=RP&lang=en-US' -UseBasicParsing | Foreach-Object Links | Where-Object outerHTML -match 'Microsoft.VCLibs.140.00.UWPDesktop_.+_x64__8wekyb3d8bbwe.appx' | Foreach-Object href) -OutFile $env:TEMP\vclibsuwp.appx
          iwr 'https://github.com/microsoft/winget-cli/releases/download/v1.1.12653/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle' -OutFile $env:TEMP\winget.msixbundle
          iwr 'https://github.com/microsoft/winget-cli/releases/download/v1.1.12653/9c0fe2ce7f8e410eb4a8f417de74517e_License1.xml' -Outfile $env:TEMP\winget.license

          Add-AppxProvisionedPackage -Online -PackagePath $env:TEMP\winget.msixbundle -LicensePath $env:TEMP\winget.license -DependencyPackagePath @("$env:TEMP\vclibs.appx", "$env:TEMP\vclibsuwp.appx")
      - name: "Verify winget"
        run: |
          winget --info
